In [1]:
from tensorflow import keras

In [2]:
keras.__version__

'2.2.4-tf'

In [3]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [6]:
len(train_labels)

60000

In [8]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
test_images.shape

(10000, 28, 28)

In [10]:
len(test_labels)

10000

In [11]:

test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [12]:
from tensorflow.keras import models
from tensorflow.keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [13]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [14]:

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [15]:
train_images.shape

(60000, 784)

In [16]:
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [17]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 4s 59us/sample - loss: 0.2565 - accuracy: 0.9268
Epoch 2/5
60000/60000 [==============================] - 2s 42us/sample - loss: 0.1055 - accuracy: 0.9687
Epoch 3/5
60000/60000 [==============================] - 3s 44us/sample - loss: 0.0697 - accuracy: 0.9795
Epoch 4/5
60000/60000 [==============================] - 3s 44us/sample - loss: 0.0503 - accuracy: 0.9844
Epoch 5/5
60000/60000 [==============================] - 3s 42us/sample - loss: 0.0372 - accuracy: 0.9890


In [18]:

test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [19]:
test_acc

0.9779

In [20]:
test_images.shape

(10000, 784)

In [21]:
test_images[0]
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [22]:
network.predict_classes(test_images)
#network.predict(test_images[0])

array([7, 2, 1, ..., 4, 5, 6])

In [23]:
import pandas as pd
import numpy as np

In [24]:
mnist_test = pd.read_csv('test.csv')

In [ ]:
X_t = mnist_test.values

In [ ]:
X_t = X_t.astype('float32')/255

In [ ]:
X_t.shape

In [ ]:
network.predict_classes(X_t)

In [ ]:
kaggle_predictions = network.predict_classes(X_t)

In [ ]:
imageid = list(range(1,len(kaggle_predictions)+1))

data = {'ImageId': imageid,'Label': kaggle_predictions}

In [ ]:
pd.DataFrame(data).to_csv('submission_CNN_Chollet.csv',index=False)